version: '3.3'
services:
  datasources:
    build: .
    volumes:
      - ./config:/config
      - ./config_private:/config_private
      - ./data:/data
      - ./update.rb:/update.rb
      - ./datasources:/datasources
    # restart: unless-stopped

  nginx:
    image: nginx
    ports:
      - 1400:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/data
#    restart: unless-stopped
