version: '3.3'
services:
  datasources:
    build: .
    volumes:
      - ./config.yaml:/config.yaml
      - ./config:/config
      - ./data:/data
    # restart: unless-stopped

  nginx:
    image: nginx
    ports:
      - 1400:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/data
#    restart: unless-stopped
